[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Tina CMS configuration
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Handle client-side routing for Astro
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Tina CMS admin
[[headers]]
  for = "/admin/*"
  [headers.values]
    Cache-Control = "no-cache"
