[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Sanity Studio configuration
[[redirects]]
  from = "/studio"
  to = "/studio/"
  status = 301

[[redirects]]
  from = "/studio/*"
  to = "/studio/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Sanity Studio
[[headers]]
  for = "/studio/*"
  [headers.values]
    Cache-Control = "no-cache"
